services:
  redis:
    image: 'redis:latest'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  db:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - '3306'
    volumes:
      - db:/var/run/mysqld
    logging:
            driver: none
    ports:
      - "33061:3306"
  web:
    build: .
    command: bundle exec rails s -p 3000 -e production -b '0.0.0.0'
    environment:
     RAILS_ENV: production
     RAILS_MAX_THREADS: 5
     BUNDLE_PATH: /bundle
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    links:
      - db
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: db
  # caddy:
  #   image: caddy:latest
  #   restart: unless-stopped
  #   command: caddy reverse-proxy --to web:3000
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - caddy:/data
  #   depends_on:
  #     - web
volumes:
  db:
  bundle:
  redis:
  # caddy:
